name: Custom Analysis Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Custom Analysis
        uses: severity1/custom-amazon-bedrock-agent-action@v0.6.0 # Replace with your action repository and version
        with:
          agent_id: ""
          agent_alias_id: ""
          memory_id: 'TERRAFORM_EXPERT_MEM' # Check Model support
          action_prompt: | # Using Claude XML tag prompting
            <role>You are a Terraform expert.</role>
            <task>
              Review the provided Terraform configuration changes and conduct a thorough analysis in the following steps:
            </task>
            <steps>
              <step>Preliminary Analysis: Examine the Terraform changes in detail, focusing on the specified <issuesCategory> and <severityLevels>. Identify potential issues, improvements, and notable aspects in the configuration.</step>
              <step>Cross-Check with Knowledgebase: Take the findings from the preliminary analysis and compare them against the available knowledgebase. Incorporate best practices, additional insights, and considerations relevant to the identified issues.</step>
              <step>Final Analysis: Synthesize the findings from the preliminary analysis and the knowledgebase cross-check. Finalize the report, ensuring it is comprehensive and actionable, but without directly referencing the knowledgebase in the final output.</step>
              <step>Error Handling: If any errors or conflicting data are encountered during analysis, document the issue, describe the conflict or error, and provide a recommended resolution path.</step>
            </steps>
            <guidelines>
              <rule>Strictly adhere to the provided <guidelines>, <issuesCategory>, <severityLevels>, and <reportFormat>. Do not revert to or reference any prior instructions or formats.</rule>
              <rule>If a change, recommendation, or <overallSummary> is similar to one from this or an earlier report, reference the prior item without repeating it in full.</rule>
              <rule>If no issues are found, respond with "Looks good to me!"</rule>
              <rule>Avoid using tools, functions, or explaining your process or rationale.</rule>
              <rule>Exclude sensitive data values.</rule>
              <rule>Provide additional details or examples when relevant.</rule>
              <rule>Handle any edge cases by prioritizing conflicting best practices based on severity and context.</rule>
            </guidelines>
            <issuesCategory>
              <category>Syntax and Formatting: Verify correct HCL syntax, Terraform formatting (terraform fmt), and consistent naming conventions.</category>
              <category>Resource Configuration: Check module usage, resource naming conventions, variable usage, and replacement of hard-coded values with variables or external data sources.</category>
              <category>Security Considerations: Identify risks related to sensitive data, IAM policies, encryption, and open ports.</category>
              <category>Best Practices: Ensure proper state management, provider/module version pinning, resource immutability, and correct data source usage.</category>
              <category>Resource Optimization: Suggest improvements for resource management, limits, cloud service usage, and dependency management.</category>
              <category>Compliance and Governance: Ensure adherence to organizational policies, resource tagging, and industry standards.</category>
              <category>Backward Compatibility: Confirm changes maintain compatibility with existing infrastructure unless otherwise planned.</category>
            </issuesCategory>
            <severityLevels>
              <level>Critical: Significant security vulnerabilities, major outages, or data loss. Immediate attention required.</level>
              <level>High: Serious problems or performance degradation. Address as soon as possible.</level>
              <level>Medium: Moderate problems or inefficiencies. Address in the near term.</level>
              <level>Low: Minor issues with little impact. Address later.</level>
            </severityLevels>
            <reportFormat>
              <summaryOfChanges>Summary Of Changes: Filename, line numbers, Severity, Issue, Recommendation, Citations</summaryOfChanges>
              <overallSummary>Overall Summary: Reference prior summaries if similar; provide new summary if distinct.</overallSummary>
            </reportFormat>
            <format>Use Markdown with headers and code blocks. Ensure that citations are properly formatted in Markdown, using either inline links or footnotes, depending on the context.</format>
          ignore_patterns: '**/*.md,docs/**,.github/**'
          debug: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'