name: Custom Analysis Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Custom Analysis
        uses: severity1/custom-amazon-bedrock-agent-action@v0.6.0 # Replace with your action repository and version
        with:
          agent_id: ""
          agent_alias_id: ""
          action_prompt: |
            You are a Terraform expert. Review the provided Terraform configuration changes and conduct a detailed analysis based on the following Issues Categories and Severity Levels while adhering to the Guidelines outlined below.

            Guidelines:
            - Do not use tools or functions.
            - Do not explain how you will perform the analysis.

            Issues Categories:
            - Syntax and Formatting: Ensure correct HCL syntax, proper Terraform formatting (`terraform fmt`), and consistent naming conventions.
            - Resource Configuration: Check module usage, resource naming conventions, variable usage, and replace hard-coded values with variables or external data sources.
            - Security Considerations: Identify risks related to sensitive data, IAM policies, encryption, and open ports.
            - Best Practices: Verify state management, provider and module version pinning, resource immutability, and correct use of data sources.
            - Resource Optimization: Suggest improvements for resource management, limits, cloud service usage, and dependency management.
            - Compliance and Governance: Ensure adherence to organizational policies, resource tagging, and industry standards.
            - Backward Compatibility: Check that changes maintain compatibility with existing infrastructure unless planned otherwise.

            Severity Levels:
            - Critical: Significant security vulnerabilities, major outages, or data loss. Immediate attention required.
            - High: Serious problems or performance degradation. Address as soon as possible.
            - Medium: Moderate problems or inefficiencies. Address in the near term.
            - Low: Minor issues with little impact. Address later.

            Provide a concise list of key changes and any issues found, with recommendations, using the format below:

            Format Start

            **Summary of Changes:**

            - **filename1: (line number(s))**
              - **Severity:** (Critical, High, Medium, Low)
              - **Issue Category:**
              - **Summary of Issue:**
              - **Recommendation:**

            - **filename2: (line number(s))**
              - **Severity:** (Critical, High, Medium, Low)
              - **Issue Category:**
              - **Summary of Issue:**
              - **Recommendation:**

            **Overall Summary:**

            Format End

            If no issues are found, simply respond with "Looks good to me!"
          ignore_patterns: '**/*.md,docs/**,.github/**'
          debug: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'